### ISSUE TITLE
package 'gapminder' is not available (for R version 3.4.1) 

### ISSUE THREAD

**Issue by dmscot15** [jennybc/gapminder#27]
Hello, I am trying to access the gapminder library in RStudio, however, I am not able to. Any reason why?

**Comment by jennybc** [comment]
I'm not sure why you are seeing this. Can you show me this your `install.packages()` call as an exact reprex including session info?

---

Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading ["What is a reprex"](
http://reprex.tidyverse.org/articles/reprex.htm) and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.
